a = input('Digite algo: ')
print(type(a))
print('é apenas espaços? ', a.isspace())
print('é alfabético? ', a.isalpha())
print('é tudo maiúscula? ', a.isupper())
print('é tudo minúscula? ', a.islower())
print('é capitalizada? ', a.istitle())
print('é numérico? ', a.isalnum())
print('é um digito? ', a.isdigit())
print('é decimal? ', a.isdecimal())
